### ISSUE TITLE
Modify config to be more compatible with Free5GC

### ISSUE THREAD

**Issue by louisroyer** [nextmn/upf#30]
instead of 
```yaml
tun-interface: upf
pfcp-address: "10.0.213.6"
gtpu-entities:
  - "10.0.201.5"
  - "10.0.215.4"
 dnn_list:
  - dnn: "sliceB"
    cidr: "10.0.111.0/24"
```
 modify to have something like:
```yaml
pfcp:
  addr: "10.0.213.6" # ip addr for listening
  nodeID: "10.0.213.6" # external ip or fqdn that can be reached
  retransTimeout: 500ms # must support `s` (seconds) but should allow more precise time
  maxRetrans: 3
gtpu:
  forwarder: "wmnsk/go-gtp"
  tunInterfaceName: upf # Name of the tun interface that will be created (optional)
  ifList:
    - addr: "10.0.201.5"
      type: N3
    - addr: "10.0.215.4"
      type: N9
dnnList:
  - dnn: "sliceB"
    cidr: "10.0.111.0/24"
  ```

Blocking issues for `addr`, `retransTimeout`, and `maxRetrans`:
- [x] https://github.com/nextmn/go-pfcp-networking/issues/22
- [x] https://github.com/nextmn/go-pfcp-networking/issues/23
